# Generated by Django 2.2.27 on 2022-11-07 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Points', models.PositiveIntegerField()),
                ('DinerNum', models.PositiveIntegerField(null=True)),
                ('PaymentMethod', models.CharField(max_length=50, null=True)),
                ('MstAddress', models.CharField(max_length=100)),
                ('MCity', models.CharField(max_length=100)),
                ('MSTATES', models.CharField(max_length=40)),
                ('MState', models.CharField(max_length=2)),
                ('MZip', models.CharField(max_length=9)),
                ('BstAddress', models.CharField(max_length=100)),
                ('BCity', models.CharField(max_length=100)),
                ('BState', models.CharField(max_length=40)),
                ('BZip', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
