# Generated by Django 2.2.27 on 2022-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='MSTATES',
        ),
        migrations.AlterField(
            model_name='profile',
            name='MState',
            field=models.CharField(max_length=40),
        ),
    ]
