# Generated by Django 4.1.1 on 2022-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
