# Generated by Django 4.1.1 on 2022-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
