# Generated by Django 4.1.1 on 2022-11-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pEmail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pPhone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
