# Generated by Django 4.1.1 on 2022-11-19 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_pemail_profile_pphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
