# Generated by Django 4.1.1 on 2022-11-19 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_profile_pphone_alter_reservation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pPhone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Phone Number', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter a valid Phone Number', regex='^(\\([0-9]{3}\\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}$')]),
        ),
    ]
