# Generated by Django 4.1.1 on 2022-11-19 20:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Time',
            field=models.DateTimeField(validators=[core.models.date_validator]),
        ),
    ]
