# Generated by Django 4.1.1 on 2022-11-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hightrafficday_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Table',
            field=models.ForeignKey(limit_choices_to={'isReserved': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.table'),
        ),
    ]
