# Generated by Django 4.1.1 on 2022-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_reservation_holdfee_reservation_ishightraffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
