# Generated by Django 4.1.1 on 2022-11-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reservation_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='TableT',
            field=models.ForeignKey(blank=True, limit_choices_to={'isReserved': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TableT', to='core.table'),
        ),
    ]
